### ISSUE TITLE
Document how to compose with

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/generator-karma#53]
It'd be great to have a documentation part on how author can use generator-karma in their own generators :)

**Comment by tomwayson** [comment]
FYI - I'm working on a generator that composes with generator-karma right now. I haven't pushed any code yet, but [I've been using the repo to track my issues](https://github.com/tomwayson/generator-esri-karma/issues).

However, I'll need something implemented for #72 in order to complete it. I submitted #73, and  @eddiemonge, it would be good to get your thoughts on the discussion there so I can finalize and submit a solid PR.

Once I complete my generator, I can add docs here or at the very least a link to it as an example of how to compose with generator-karma.

**Comment by tomwayson** [comment]
@SBoudrias @eddiemonge 

Now that #73 has been merged, I'm all set to publish [my generator](https://github.com/tomwayson/generator-esri-karma) as soon as this repo bumps major and publishes a 1.0.0 release.

Then I can make a small PR here adding instructions to the README on how to compose with this generator. Basically calling `composeWith()` [in a function](https://github.com/tomwayson/generator-esri-karma/blob/master/app/index.js#L76) with `default` priority in the [run loop](http://yeoman.io/authoring/running-context.html).

**Comment by SBoudrias** [comment]
Hey @tomwayson, this generator is really poorly written. Would you be willing to update it to yeoman-generator 0.19.0 and use the new `this.fs` file helpers.

I'm scared in the state it is right now it'll be hard to get anyone to compose with this generator.

**Comment by tomwayson** [comment]
@SBoudrias, well, I am trying to compose with this generator so that's at least one person ;) 

Looks like @alfonso-presa is already on this w/ #76. 

At the very least I can make a few comments there as well as test it out in my generator that composes with this.

**Comment by SBoudrias** [comment]
@tomwayson That would be great!
